# Minimal LiveKit config
port: 7880
rtc:
  tcp_port: 7881
  udp_port: 7881
keys:
  # This gets replaced by docker compose from your .env file
  # Do not commit your keys here.
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
logging:
  level: info
